### ISSUE TITLE
Calculate overall percentages of web browsing

### ISSUE THREAD

**Issue by jgknight** [pmarks-net/ipvfoo#22]
This is a feature request, to add the ability to see what percentage of my *overall* web traffic is IPv6 vs IPv4 since installing the plugin.

You could aggregate visits into a simple database, perhaps just the number of IPv4 requests and the number of IPv6 requests.  Then instead of seeing overall, you could break it down by month or day, etc.

**Comment by pmarks-net** [comment]
The IPvFoo codebase is centered on collating real-time data, and then throwing it away as quickly as possible.  History/Analytics is an orthogonal problem, which could be implemented as a separate extension with minimal opportunity for code reuse.

Your idea is entirely reasonable, but I consider it to be beyond the scope of this project, and have no interest in implementing it.
