### ISSUE TITLE
Add this addon on addons.mozilla.org

### ISSUE THREAD

**Issue by AlexBeLi** [pmarks-net/ipvfoo#28]
I installed this addon from chrome.google.com on Firefox 55 using addon Chrome Store Foxified. This addon patched manifest.json. It looks like all works is fine and this addon can be used instead of IPvFox.
[https://developer.mozilla.org/en-US/Add-ons/WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)

**Comment by pmarks-net** [comment]
Hm... this may be worth doing, though it will mean exposure to twice as many bugs.  For example, Firefox seems to be sizing the popup window too small, with horizontal scrollbars.

**Comment by pmarks-net** [comment]
Let's discuss in #29, because it has a pull request.
