### ISSUE TITLE
access denied instead of IP

### ISSUE THREAD

**Issue by nshopik** [pmarks-net/ipvfoo#31]
I've noticed recently that some sites give me `access denied` instead IP of hostname for example https://coin.dance/ but pretty much everything else works just fine

**Comment by pmarks-net** [comment]
Chrome's network debugger says:

    Request URL:https://coin.dance/
    Request Method:GET
    Status Code:200 OK (from ServiceWorker)

The sequence of IPvFoo-relevant events is:
- `webRequest.onBeforeRequest`
- `webRequest.onResponseStarted` (fromCache=true, no IP address.)
- `webNavigation.onCommitted`

So coin.dance is using a ServiceWorker, which bypasses the `onSendHeaders` event that https://github.com/pmarks-net/ipvfoo/commit/45bfb4e0b1693c98894c5e616fa40710204c9d2a assumed would be present for all requests.  That commit also broke `file://` URLs.

This means that it's necessary to handle both `onBeforeRequest` and `onSendHeaders` to get the full picture.

**Comment by pmarks-net** [comment]
Note that version 1.39 still shows a `?` for https://coin.dance/ because the ServiceWorker requests don't report any IP addresses.

But you should see all the domains now, instead of `(access denied)`.

**Comment by nshopik** [comment]
Yeah it will now show `(no address)` for coin.dance at least, but also for all other domains on this page too not sure if it was intended? Like `fonts.gstatic.com` also reported as `(no address)` too

**Comment by pmarks-net** [comment]
Fixed in https://github.com/pmarks-net/ipvfoo/commit/d59dcf5227c2449da175d5629c1948c3d2f11f25
