### ISSUE TITLE
Update icon to look good on dark themes

### ISSUE THREAD

**Issue by Gunni** [pmarks-net/ipvfoo#33]
![asd](https://user-images.githubusercontent.com/358099/30144544-58ec3f6a-937b-11e7-87e3-435d95f13cfa.png)

**Comment by pmarks-net** [comment]
Easier said than done, unless you're aware of some way for an extension to determine the background color.

**Comment by Gunni** [comment]
Maybe add an option page to select icon from a list?

**Comment by Gunni** [comment]
Looks amazing, thanks!
