### ISSUE TITLE
A better Font?

### ISSUE THREAD

**Issue by QIEXXII** [pmarks-net/ipvfoo#36]
enhancement
-----
What about use Microsoft YaHei UI font on Windows?

**Comment by pmarks-net** [comment]
I think the current sprites look fine, but you're welcome to attach your own design for consideration:

https://github.com/pmarks-net/ipvfoo/blob/master/src/sprites16.png
https://github.com/pmarks-net/ipvfoo/blob/master/src/sprites32.png
