### ISSUE TITLE
Edge support?

### ISSUE THREAD

**Issue by cerebrate** [pmarks-net/ipvfoo#37]
Would it be possible to add support for the Microsoft Edge browser?

This is the one extension I miss from Chrome... :)

**Comment by pmarks-net** [comment]
I have no interest in this browser.

**Comment by samkatakouzinos** [comment]
> I have no interest in this browser.

Will you reconsider now that Microsoft Edge is Chrome based?
May you package this extension as a native add-on?
https://www.microsoft.com/store/collections/EdgeExtensions

**Comment by pmarks-net** [comment]
When the new Edge showed up on my Windows machine, I was able to install IPvFoo from https://chrome.google.com/webstore/detail/ecanpcehffngcegjmadlcijfolapggal

Are there any practical scenarios where this doesn't work?  I'm not sure if I want to bother maintaining another store entry.

**Comment by samkatakouzinos** [comment]
There are zero practical scenarios where this doesn't work. 
The technically minded will be able to get a Chrome extension into Edge.

The only reason I see to repackage for Edge is for visibility of extension for non-technically minded users.
