### ISSUE TITLE
Firefox BGP.HE

### ISSUE THREAD

**Issue by maisonmdsgreen** [pmarks-net/ipvfoo#38]
Add option bgp.he in Firefox equal Google Chrome

Thanks

**Comment by pmarks-net** [comment]
It works for me on Firefox 58, but only if I bring up the context menu a second time.  I think Firefox has a compatibility bug, where you can't update the `enabled` state from an `oncontextmenu` handler.

**Comment by pmarks-net** [comment]
I reported https://bugzilla.mozilla.org/show_bug.cgi?id=1439497 .  https://github.com/pmarks-net/ipvfoo/issues/32 tracks all the Firefox bugs.
