### ISSUE TITLE
Cannot display IP when web come from serviceworker.

### ISSUE THREAD

**Issue by steven7851** [pmarks-net/ipvfoo#40]
![snipaste_20180516_022758](https://user-images.githubusercontent.com/6252238/40076312-25afa23a-58b1-11e8-956e-38af3800b32d.png)![snipaste_20180516_023240](https://user-images.githubusercontent.com/6252238/40076421-6caa5018-58b1-11e8-8c07-c9894143c219.png)

**Comment by pmarks-net** [comment]
I noted in https://github.com/pmarks-net/ipvfoo/issues/31#issuecomment-311557094 that Chrome just isn't reporting addresses for these.

**Comment by pmarks-net** [comment]
Fixed in https://github.com/pmarks-net/ipvfoo/commit/d59dcf5227c2449da175d5629c1948c3d2f11f25
