### ISSUE TITLE
web.whatsapp.com shows as access denied on chrome version 71

### ISSUE THREAD

**Issue by anzetal** [pmarks-net/ipvfoo#42]
web.whatsapp.com worked fine till chrome 70. (Access denied) shows up after the update to 71

**Comment by pmarks-net** [comment]
When I visit https://web.whatsapp.com (after linking it to my phone), there is no `webRequest.onBeforeRequest(main_frame)` event fired at any time.  This event is critical to IPvFoo's state machine, so I don't think it can be fixed without complaining to Chrome.

**Comment by pmarks-net** [comment]
The `(access denied)` mode no longer exists: https://github.com/pmarks-net/ipvfoo/commit/df46293e9e643e3a18d5b34678fcd8d24bff26d1
