### ISSUE TITLE
How if the domain is also available in IPv6

### ISSUE THREAD

**Issue by tiagogaspar8** [pmarks-net/ipvfoo#48]
Hi,

I'd like to request a feature that shows if the domain is available on IPv6 even if it is connected via IPv4. This might be useful because of Happy Eyeballs algorithm or simply because the IPv6 website might be down, and it would be great having the insight without having to resolve each one manually.
As a suggestion, this can be done by having a "6" beside the hostname or beside the IPv4 address like the socket one.

Thanks!

**Comment by pmarks-net** [comment]
You can right-click the domain and select "Look up on bgp.he.net".

Chrome does not have an API for resolving DNS that I'm aware of.

**Comment by tiagogaspar8** [comment]
That's an improvement, although it would be really nice to have that info right on the windows instead of doing it one by one.

**Comment by LucasMZReal** [comment]
@pmarks-net DNS over HTTPS?
