### ISSUE TITLE
Show ASN/ORG in addr_table

### ISSUE THREAD

**Issue by rootbeerdan** [pmarks-net/ipvfoo#49]
I'm not sure if it would be more useful to have Org or ASN in the output (or both?), but I wanted to keep clutter to a minimum, so I envisioned something like this:

![ipvfoo with AS ORG name](https://global.danielmarks.dev/sx/2023/NAoubU0Ofn.png)

Or with ASNs:

![ipvfoo with AS ORG name](https://global.danielmarks.dev/sx/2023/cRodzJ8qx1.png)

The difficulty would be implementing and managing WHOIS queries, so it might be better for privacy and performance to make this setting optional (off by default), and only query a WHOIS service when someone actually opens up the table. 

I'm happy to take a crack at this if this is something considered in scope for this extension.

**Comment by pmarks-net** [comment]
"Everything is captured and displayed privately, without creating any additional network traffic." -- I'd rather stick to that design principle, and not include information fetched from the internet.

**Comment by rootbeerdan** [comment]
I had a couple POCs, but they all involved significantly complicating the actual purpose of the extension. I'll close this, but I appreciate the feedback.
