### ISSUE TITLE
No way to pin extension to toolbar in Firefox

### ISSUE THREAD

**Issue by nimblemachines** [pmarks-net/ipvfoo#56]
Maybe I'm going crazy, or maybe Firefox is, but I tried installing ipvfoo several times, in all versions of Firefox (normal, Beta, Developer), and it seems there is no way to pin it to the toolbar - which makes it pretty useless!

After installing ipvfoo and clicking on the "puzzle piece" extensions icon, the gear icon menu for ipvfoo doesn't show the "pin to toolbar" option, like it does for other the other extensions that I have installed.

I have no idea how extensions work, so I haven't tried to debug the issue.

Am I going crazy?

I have had this extension installed on Chrome for years, and I love it! I'd very much like to use it on Firefox as well.

**Comment by pmarks-net** [comment]
Do you see it in the location bar, per these [screenshots](https://addons.mozilla.org/en-US/firefox/addon/ipvfoo/)?

**Comment by nimblemachines** [comment]
Ah. I was used to how it works in Chrome. I wasn't expecting to see the icon anywhere else. I guess I didn't pay attention to the screenshots on the addon page.

It *does* work as you say, with the icon in the address bar.

So I'm not crazy, but maybe I *am* an idiot. ;-)

Thanks for your help!

**Comment by pmarks-net** [comment]
It used to be in Chrome's address bar too.  Chrome killed the `pageAction` feature, but Firefox kept it.

![](https://raw.githubusercontent.com/pmarks-net/ipvfoo/master/misc/screenshot3.png)
