### ISSUE TITLE
Can't pin or use the extension on Firefox

### ISSUE THREAD

**Issue by navjotjsingh** [pmarks-net/ipvfoo#57]
The button to pin the extension in Firefox is missing. And one can't use it by just clicking on the extension dropdown. I am using Firefox 126.0.1 and Windows 10. The bug is persistent even on Firefox 127.

**Comment by mbunkus** [comment]
I have the same issue with Firefox 127.0.2 on Linux. Not sure why you closed the issue. Did you get it working again?

**Comment by pmarks-net** [comment]
Did you look in the address bar?

![](https://github.com/pmarks-net/ipvfoo/blob/master/misc/screenshot_firefox.png?raw=true)
